module.exports = {
  Create: function(n){
    n.click('div#tab-1')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Return')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-1')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Light')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-2')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Heater')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-3')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Skimmer')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-4')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Fan')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-5')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'ATOPump')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-6')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)
    return(function(){
      return('Equipment created')
    })
  }
}
