const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true })

function TestEquipments () {
  nightmare
    .goto('http://localhost:8080/')
    .viewport(1100, 650)
    .wait(500)
    .type('input#reef-pi-user', 'reef-pi')
    .wait(500)
    .type('input#reef-pi-pass', 'reef-pi')
    .wait(500)
    .click('input#btnSaveCreds')
    .wait(500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Return')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-1')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Light')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-2')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Heater')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-3')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Skimmer')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-4')
    .wait(1000)
    .click('input#createEquipment')

    .wait(2500)
    .evaluate(function () { return 'equipments' })
    .end()
      .then(function (result) {
        console.log(result)
      })
      .catch(function (error) {
        console.error('Error:', error)
      })
}
TestEquipments()
