const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true, dock: true, typeInterval: 120 })

function TestOutlets () {
  nightmare
    .goto('http://localhost:8080/')
    .viewport(1200,900)
    .wait(500)
    .type('input#reef-pi-user', 'reef-pi')
    .wait(500)
    .type('input#reef-pi-pass', 'reef-pi')
    .wait(500)
    .click('input#btnSaveCreds')
    .wait(500)
    .click('li#react-tabs-16')
    .wait(500)
    .click('button#connectors')
    .wait(500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O1')
    .wait(500)
    .type('input#outletPin', '1')
    .wait(500)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O2')
    .wait(500)
    .type('input#outletPin', '2')
    .wait(500)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O3')
    .wait(500)
    .type('input#outletPin', '3')
    .wait(500)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O4')
    .wait(500)
    .type('input#outletPin', '4')
    .wait(500)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_jack')
    .wait(500)
    .type('input#jackName', 'J1')
    .wait(500)
    .type('input#jackPins', '1,2')
    .wait(500)
    .click('input#createJack')
    .wait(2500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Return')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-1')
    .wait(500)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Light')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-2')
    .wait(500)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Heater')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-3')
    .wait(500)
    .click('input#createEquipment')
    .wait(1500)

    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Skimmer')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-4')
    .wait(500)
    .click('input#createEquipment')

    .wait(2500)
    .evaluate(function () { return 'outlets' })
    .end()
      .then(function (result) {
        console.log(result)
      })
      .catch(function (error) {
        console.error('Error:', error)
      })
}
TestOutlets()
