const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true, dock: true, typeInterval: 120 })

function SmokeTest () {
  nightmare
    .goto('http://localhost:8080/')
    .viewport(1100, 650)
    .wait(500)

     // sign in
    .type('input#reef-pi-user', 'reef-pi')
    .wait(500)
    .type('input#reef-pi-pass', 'reef-pi')
    .wait(500)
    .click('input#btnSaveCreds')
    .wait(1500)

     // create outlets
    .click('li#react-tabs-18')
    .wait(500)
    .click('button#btn-connectors')
    .wait(500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O1')
    .wait(500)
    .type('input#outletPin', '6')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O2')
    .wait(500)
    .type('input#outletPin', '12')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O3')
    .wait(500)
    .type('input#outletPin', '13')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O4')
    .wait(500)
    .type('input#outletPin', '19')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O5')
    .wait(500)
    .type('input#outletPin', '16')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O6')
    .wait(500)
    .type('input#outletPin', '26')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O7')
    .wait(500)
    .type('input#outletPin', '20')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

    .click('input#add_outlet')
    .wait(500)
    .type('input#outletName', 'O8')
    .wait(500)
    .type('input#outletPin', '21')
    .wait(1000)
    .click('input#createOutlet')
    .wait(1500)

     // create inlet
    .click('input#add_inlet')
    .wait(500)
    .type('input#inletName', 'I1')
    .wait(500)
    .type('input#inletPin', '25')
    .wait(1000)
    .click('input#createInlet')
    .wait(1500)

    .click('input#add_inlet')
    .wait(500)
    .type('input#inletName', 'I2')
    .wait(500)
    .type('input#inletPin', '23')
    .wait(1000)
    .click('input#createInlet')
    .wait(1500)

    .click('input#add_inlet')
    .wait(500)
    .type('input#inletName', 'I3')
    .wait(500)
    .type('input#inletPin', '27')
    .wait(1000)
    .click('input#createInlet')
    .wait(1500)

    // create jack
    .click('input#add_jack')
    .wait(500)
    .type('input#jackName', 'J0')
    .wait(500)
    .type('input#jackPins', '0')
    .wait(1000)
    .click('input#createJack')
    .wait(1500)

    .click('input#add_jack')
    .wait(500)
    .type('input#jackName', 'J1')
    .wait(500)
    .type('input#jackPins', '1,2')
    .wait(1000)
    .click('input#createJack')
    .wait(1500)

    // create equipments
    .click('li#react-tabs-2')
    .wait(500)
    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Return')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-1')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Light')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-2')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Heater')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-3')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Skimmer')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-4')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'Fan')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-5')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    .click('input#add_equipment')
    .wait(500)
    .type('input#equipmentName', 'ATOPump')
    .wait(500)
    .click('button#outlet')
    .wait(500)
    .click('span#outlet-6')
    .wait(1000)
    .click('input#createEquipment')
    .wait(1500)

    // Setup lighting
    .click('li#react-tabs-6')
    .wait(500)
    .click('input#add_light')
    .wait(500)
    .type('input#lightName', 'A360')
    .wait(500)
    .click('button#jack')
    .wait(500)
    .click('span#select-jack-J1')
    .wait(1000)
    .click('input#createLight')
    .wait(500)
    .click('input#A360-channel-1-auto')
    .wait(500)
    .click('input#A360-channel-2-auto')
    .wait(500)
    .click('input#update-light-A360')
    .wait(1500)

    .click('li#react-tabs-6')
    .wait(500)
    .click('input#add_light')
    .wait(500)
    .type('input#lightName', 'MoonLight')
    .wait(500)
    .click('button#jack')
    .wait(500)
    .click('span#select-jack-J0')
    .wait(1000)
    .click('input#createLight')
    .wait(1500)

    // ph
    .click('li#react-tabs-12')
    .wait(500)
    .click('input#add_probe')
    .wait(500)
    .type('input#new_probe_name', 'Biocube29')
    .wait(500)
    .click('input#new_probe_enable')
    .wait(500)
    .type('input#new_probe_period')
    .type('input#new_probe_period', 5)
    .wait(500)
    .click('input#create_probe')
    .wait(1500)

    // Setup auto top off
    .click('li#react-tabs-10')
    .wait(1000)
    .click('input#add_new_ato_sensor')
    .wait(1000)
    .type('input#new_ato_sensor_name', 'Biocube29')
    .wait(500)
    .click('button#new_ato-inlet')
    .wait(500)
    .click('span#new_ato-2')
    .wait(500)
    .click('input#new_ato_sensor_enable')
    .wait(500)
    .type('input#new_ato_sensor_period')
    .type('input#new_ato_sensor_period', 120)
    .wait(500)
    .click('input#create_ato')
    .wait(1500)

    // set up doser
    .click('li#react-tabs-14')
    .wait(500)
    .click('input#add_doser')
    .wait(500)
    .type('input#doser_name','Two Part - CaCO3')
    .wait(500)
    .click('button#new_doserjack')
    .wait(500)
    .click('span#new_doser-J0')
    .wait(500)
    .click('input#create_pump')
    .wait(500)
    .click('input#schedule-pump-1')
    .wait(500)
    .click('input#pump-enable-1')
    .wait(500)
    .type('input#day')
    .type('input#day', '*')
    .wait(500)
    .type('input#hour')
    .type('input#hour', '1,9,17')
    .wait(500)
    .type('input#minute')
    .type('input#minute', '1')
    .wait(500)
    .type('input#second')
    .type('input#second', '1')
    .wait(500)
    .type('input#set-duration-1')
    .type('input#set-duration-1', '15')
    .wait(500)
    .click('input#set-schedule-1')
    .wait(1500)

    // Setup temperature controller
    .click('li#react-tabs-8')
    .wait(500)
    .click('input#add_tc')
    .wait(500)
    .type('input#new_tc_name', 'Biocube29')
    .wait(500)
    .type('input#new_tc_period')
    .type('input#new_tc_period', 120)
    .wait(500)
    .click('button#new_tc_sensor')
    .wait(500)
    .click('span#new_tc_sensor-28-04177049bcff')
    .wait(500)
    .click('input#create_tc')
    .wait(1500)
    .click('li#react-tabs-0')
    .wait(2500)

    .click('li#react-tabs-8')
    .wait(500)
    .click('input#update-tc-1')
    .wait(500)
    .click('input#tc_control_1')
    .wait(500)
    .type('input#tc_control_min-1')
    .type('input#tc_control_min-1', '78.5')
    .wait(500)
    .type('input#tc_control_max-1')
    .type('input#tc_control_max-1', '79.3')
    .wait(500)
    .click('button#heater_selector-1')
    .wait(500)
    .click('span#heater_selector-1-Heater')
    .wait(500)
    .click('button#cooler_selector-1')
    .wait(500)
    .click('span#cooler_selector-1-Fan')
    .wait(500)
    .click('input#update-tc-1')

    .click('li#react-tabs-10')
    .wait(500)
    .click('input#updateATO')
    .wait(500)
    .click('input#ato_control')
    .wait(500)
    .click('button#ato-pump')
    .wait(500)
    .click('span#ato-pump-ATOPump')
    .wait(500)
    .click('input#updateATO')
    .wait(1500)

    // Configure dashboard

    .click('li#react-tabs-18')
    .wait(500)
    .click('button#btn-dashboard')
    .wait(500)
    .type('input#to-row-row')
    .type('input#to-row-row', '3')
    .wait(500)
    .type('input#to-row-column')
    .type('input#to-row-column', '2')
    .wait(500)

    .click('button#db-0-0')
    .wait(500)
    .click('span#temperature-chart-0-0')
    .wait(500)
    .click('span#component-temperature-0-0-1')
    .wait(500)

    .click('button#db-0-1')
    .wait(500)
    .click('span#ph-current-chart-0-1')
    .wait(500)
    .click('span#component-ph-current-0-1-1')
    .wait(500)

    .click('button#db-1-0')
    .wait(500)
    .click('span#ato-chart-1-0')
    .wait(500)
    .click('span#component-ato-1-0-1')
    .wait(500)

    .click('button#db-1-1')
    .wait(500)
    .click('span#equipment-chart-1-1')
    .wait(500)

    .click('button#db-2-0')
    .wait(500)
    .click('span#light-chart-2-0')
    .wait(500)
    .click('span#component-light-2-0-1')
    .wait(500)

    .click('button#db-2-1')
    .wait(500)
    .click('span#health-chart-2-1')
    .wait(500)
    .click('span#component-health-2-1-current')
    .wait(500)
    .click('input#save_dashboard')
    .wait(1500)

    // Create timer

    .click('li#react-tabs-4')
    .wait(500)
    .click('input#add_timer')
    .wait(500)
    .type('input#name')
    .type('input#name', 'Nightly Skimmer Run')
    .wait(500)
    .click('input#equipment')
    .wait(500)
    .click('button#equipment')
    .wait(500)
    .click('span#equipment-4')
    .wait(500)
    .click('input#equipment-revert')
    .wait(500)
    .type('input#equipment-action-duration')
    .type('input#equipment-action-duration', 60*60*8)
    .wait(500)
    .type('input#hour')
    .type('input#hour', 22)
    .wait(500)
    .type('input#minute')
    .type('input#minute', 2)
    .wait(500)
    .type('input#second')
    .type('input#second', 5)
    .wait(500)
    .click('input#createTimer')
    .wait(1000)

    .click('li#react-tabs-0')
		.wait(1500)
    .end()
      .then(function () {
        console.log('Smoking Hot!')
      })
      .catch(function (error) {
        console.error('Error:', error)
        process.exit(-1)
      })
}
SmokeTest()
