module.exports = {
  Configure: function(n){
    n.click('a#tab-temperature')
    .wait(500)
    .click('input#add_tc')
    .wait(500)
    .type('input#new_tc_name', 'Biocube29')
    .wait(500)
    .type('input#new_tc_period')
    .type('input#new_tc_period', 120)
    .wait(500)
    .click('button#new_tc_sensor')
    .wait(500)
    .click('span#new_tc_sensor-28-04177049bcff')
    .wait(500)
    .click('input#create_tc')
    .wait(1500)
    .click('a#tab-dashboard')
    .wait(2500)

    .click('a#tab-temperature')
    .wait(500)
    .click('input#expand-tc-1')
    .wait(500)
    .click('input#update-tc-1')
    .wait(500)
    .click('input#tc_control_1')
    .wait(500)
    .type('input#tc_control_min-1')
    .type('input#tc_control_min-1', '78.5')
    .wait(500)
    .type('input#tc_control_max-1')
    .type('input#tc_control_max-1', '79.3')
    .wait(500)
    .click('button#heater_selector-1')
    .wait(500)
    .click('span#heater_selector-1-Heater')
    .wait(500)
    .click('button#cooler_selector-1')
    .wait(500)
    .click('span#cooler_selector-1-Fan')
    .wait(500)
    .click('input#update-tc-1')

    return(function(){
      return('Temperure controller configured')
    })
  }
}
