module.exports = {
  Create: function (n) {
    n.click('a#tab-timers')
      .wait(500)
      .click('input#add_timer')
      .wait(500)
      .type('input#name')
      .type('input#name', 'Nightly Skimmer Run')
      .wait(500)
      .click('input#new-timer-enable')
      .wait(500)
      .click('button#new-timer-equipment')
      .wait(500)
      .click('span#new-timer-equipment-4')
      .wait(500)
      .click('input#new-timer-equipment-revert')
      .wait(500)
      .type('input#new-timer-equipment-action-duration')
      .type('input#new-timer-equipment-action-duration', 60 * 60 * 8)
      .wait(500)
      .type('input#new-timer-hour')
      .type('input#new-timer-hour', 22)
      .wait(500)
      .type('input#new-timer-minute')
      .type('input#new-timer-minute', 2)
      .wait(500)
      .type('input#new-timer-second')
      .type('input#new-timer-second', 5)
      .wait(500)
      .click('input#createTimer')
      .wait(1000)
    return function () {
      return ('Timer created')
    }
  }
}
