module.exports = {
  Create: function(n){
    n.click('li#react-tabs-4')
    .wait(500)
    .click('input#add_timer')
    .wait(500)
    .type('input#name')
    .type('input#name', 'Nightly Skimmer Run')
    .wait(500)
    .click('input#equipment')
    .wait(500)
    .click('button#equipment')
    .wait(500)
    .click('span#equipment-4')
    .wait(500)
    .click('input#equipment-revert')
    .wait(500)
    .type('input#equipment-action-duration')
    .type('input#equipment-action-duration', 60*60*8)
    .wait(500)
    .type('input#hour')
    .type('input#hour', 22)
    .wait(500)
    .type('input#minute')
    .type('input#minute', 2)
    .wait(500)
    .type('input#second')
    .type('input#second', 5)
    .wait(500)
    .click('input#createTimer')
    .wait(1000)
    return(function(){
      return('Timer created')
    })
  }
}
