package telemetry

import (
	"errors"
	"net/http"
	"time"

	"github.com/reef-pi/reef-pi/controller/storage"
	"github.com/reef-pi/reef-pi/controller/utils"
)

// PasswordStoredPlaceholder and AdafruitIOTokenStoredPlaceholder are sentinel
// values returned for stored secrets and accepted on update to preserve the
// existing secret value.
const PasswordStoredPlaceholder = "<stored>"
const AdafruitIOTokenStoredPlaceholder = "<stored>"

func (t *telemetry) GetConfig(w http.ResponseWriter, req *http.Request) {
	fn := func(_ string) (interface{}, error) {
		c, err := t.configRepository().get()
		if err != nil {
			return nil, err
		}
		if c.AdafruitIO.Token != "" {
			c.AdafruitIO.Token = AdafruitIOTokenStoredPlaceholder
		}
		if c.Mailer.Password != "" {
			c.Mailer.Password = PasswordStoredPlaceholder
		}
		return &c, nil
	}
	utils.JSONGetResponse(fn, w, req)
}

func (t *telemetry) UpdateConfig(w http.ResponseWriter, req *http.Request) {
	var c TelemetryConfig

	existingConfig, readErr := t.configRepository().get()
	if readErr != nil {
		if errors.Is(readErr, storage.ErrDoesNotExist) {
			utils.ErrorResponse(http.StatusInternalServerError, "Failed to update. Error: "+readErr.Error(), w)
			return
		}
	}

	fn := func(_ string) error {
		if readErr == nil {
			if c.AdafruitIO.Token == AdafruitIOTokenStoredPlaceholder {
				c.AdafruitIO.Token = existingConfig.AdafruitIO.Token
			}
			if c.Mailer.Password == PasswordStoredPlaceholder {
				c.Mailer.Password = existingConfig.Mailer.Password
			}
		}
		if err := t.configRepository().update(c); err != nil {
			return err
		}
		t.applyConfig(c)
		return nil
	}
	utils.JSONUpdateResponse(&c, fn, w, req)
}

func (t *telemetry) SendTestMessage(w http.ResponseWriter, req *http.Request) {
	fn := func(_ string) error {
		_, err := t.Alert("Test email", "This is a test email, generated by reef-pi at: "+time.Now().Format(time.RFC822))
		return err
	}
	utils.JSONDeleteResponse(fn, w, req)
}
