name: Frontend Checks
on:
  push:
    paths:
      - '**/*.jsx'
      - '*.json'
      - 'yarn.lock'
      - 'Makefile'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '**/*.jsx'
      - '*.json'
      - 'yarn.lock'
      - 'Makefile'
      - '.github/workflows/*.yml'

jobs:
  jest-standard:
    name: Jest and Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn
      - name: standard
        run: make standard
      - name: jest
        run: yarn run jest-update-snapshot

  translations:
    name: Translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/cache@v5.0.5
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install
        run: yarn
      - name: Check Translations
        run: yarn run translations:chk
