name: Go CI
on: [push, pull_request]
jobs:
  backend:
    name: Go Tests and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.1
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: make lint
      - run: make race
