name: Frontend Jest
on: [push, pull_request]
jobs:
  frontend-jest:
    name: Jest and Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
      - uses: actions/cache@v4.3.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node-26-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-26-node_modules-
      - name: Install
        run: yarn
      - name: standard
        run: make standard
      - name: jest
        run: yarn run jest-update-snapshot
