name: jest
on: [push, pull_request]
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/cache@v4.3.0
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v2-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn
      - name: standard
        run: make standard
      - name: jest
        run: yarn run jest-update-snapshot
